/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand. */

/** Семантические стили типографики: конфликтуют друг с другом, но не с цветом. */
export const textStyleClassNames = [
  'text-display-hero',
  'text-display-editorial',
  'text-heading-1',
  'text-heading-2',
  'text-heading-3',
  'text-heading-4',
  'text-card-title',
  'text-quote',
  'text-body-lg',
  'text-body',
  'text-body-sm',
  'text-caption',
  'text-eyebrow',
  'text-label',
  'text-button',
  'text-price',
  'text-numeric',
] as const;

/** Длительности переходов из шкалы движения. */
export const durationClassNames = [
  'duration-instant',
  'duration-fast',
  'duration-normal',
  'duration-slow',
  'duration-slower',
  'duration-cinematic',
  'duration-marquee',
  'duration-ken-burns',
] as const;

/** Слои из карты z-index. */
export const zIndexClassNames = [
  'z-base',
  'z-raised',
  'z-sticky',
  'z-header',
  'z-scroll-progress',
  'z-dropdown',
  'z-drawer',
  'z-modal',
  'z-popover',
  'z-toast',
  'z-tooltip',
  'z-command-palette',
] as const;
