/**
 * Генератор `src/styles/tokens.css` из TypeScript-токенов.
 *
 *   npm run tokens:build   — перегенерировать файл
 *   npm run tokens:check   — упасть, если файл разошёлся с TS (запускается в CI)
 *
 * Смысл: значения живут в TS (типизированы, доступны рантайму), а CSS —
 * производный артефакт. Двойного источника правды не существует.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { schemeTokens, textStyles, tokens } from '../src/design/tokens/index.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(HERE, '..', 'src', 'styles', 'tokens.css');
const BANNER = '/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand. */';

type Flat = Array<[string, string]>;

/** `{ a: { b: 1 } }` -> `[['a-b', '1']]` с kebab-case ключами. */
function flatten(prefix: string, value: unknown, out: Flat = []): Flat {
  if (value === null || typeof value !== 'object') {
    out.push([prefix, String(value)]);
    return out;
  }
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    const kebab = key
      .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
      .replace(/_/g, '-')
      .toLowerCase();
    flatten(prefix ? `${prefix}-${kebab}` : kebab, child, out);
  }
  return out;
}

function block(selector: string, entries: Flat, indent = '  '): string {
  const body = entries.map(([name, value]) => `${indent}--${name}: ${value};`).join('\n');
  return `${selector} {\n${body}\n}`;
}

function buildScaleBlock(): string {
  const entries: Flat = [];
  flatten('font-family', tokens.fontFamily, entries);
  flatten('font-weight', tokens.fontWeight, entries);
  flatten('text', tokens.fontSize, entries);
  flatten('leading', tokens.lineHeight, entries);
  flatten('tracking', tokens.letterSpacing, entries);
  flatten('space', tokens.space, entries);
  flatten('layout', tokens.layout, entries);
  flatten('radius', tokens.radius, entries);
  flatten('border-width', tokens.borderWidth, entries);
  flatten('ease', tokens.easing, entries);
  flatten('duration', tokens.duration, entries);
  flatten('z', tokens.zIndex, entries);
  flatten('aspect', tokens.aspectRatio, entries);
  flatten('opacity', tokens.opacity, entries);
  flatten('scrim', tokens.scrim, entries);
  return block(':root', entries);
}

/**
 * Breakpoints регистрируются через `@theme` литеральными значениями:
 * media query не может содержать `var()`, поэтому здесь `inline`-ссылка
 * на переменную невозможна в принципе.
 */
function buildBreakpointTheme(): string {
  const entries: Flat = Object.entries(tokens.breakpoint).map(
    ([name, px]) => [`breakpoint-${name}`, `${px}px`] as [string, string],
  );
  return block('@theme', entries);
}

function buildSchemeBlocks(): string {
  return Object.entries(schemeTokens)
    .map(([scheme, { colors, shadows }]) => {
      const entries: Flat = [
        ...Object.entries(colors),
        ...Object.entries(shadows),
        ['color-scheme-name', scheme],
      ];
      const selector =
        scheme === 'light'
          ? ':root,\n[data-theme="light"]'
          : `[data-theme="${scheme}"]`;
      const extra = scheme === 'light' ? '  color-scheme: light;' : '  color-scheme: dark;';
      const body = entries.map(([n, v]) => `  --${n}: ${v};`).join('\n');
      return `${selector} {\n${extra}\n${body}\n}`;
    })
    .join('\n\n');
}

function buildTextStyleUtilities(): string {
  return Object.entries(textStyles)
    .map(([name, s]) => {
      return [
        `[data-text="${name}"], .text-${name} {`,
        `  font-family: var(--font-family-${s.family});`,
        `  font-size: var(--text-${s.size});`,
        `  font-weight: var(--font-weight-${s.weight});`,
        `  line-height: var(--leading-${s.lineHeight});`,
        `  letter-spacing: var(--tracking-${s.tracking});`,
        `}`,
      ].join('\n');
    })
    .join('\n\n');
}

function render(): string {
  return [
    BANNER,
    '',
    buildBreakpointTheme(),
    '',
    buildScaleBlock(),
    '',
    buildSchemeBlocks(),
    '',
    '/* Semantic text styles — используйте data-text="heading-2" или класс .text-heading-2 */',
    buildTextStyleUtilities(),
    '',
  ].join('\n');
}

const next = render();
const isCheck = process.argv.includes('--check');

if (isCheck) {
  let current = '';
  try {
    current = readFileSync(OUT_FILE, 'utf8');
  } catch {
    console.error(`tokens:check — ${OUT_FILE} отсутствует. Запустите: npm run tokens:build`);
    process.exit(1);
  }
  if (current.replace(/\r\n/g, '\n') !== next) {
    console.error('tokens:check — tokens.css устарел. Запустите: npm run tokens:build');
    process.exit(1);
  }
  console.log('tokens:check — OK');
} else {
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, next, 'utf8');
  console.log(`tokens:build — записано ${OUT_FILE}`);
}
