/**
 * Генератор `src/styles/tokens.css` из TypeScript-токенов.
 *
 *   npm run tokens:build   — перегенерировать файл
 *   npm run tokens:check   — упасть, если файл разошёлся с TS (запускается в CI)
 *
 * Смысл: значения живут в TS (типизированы, доступны рантайму), а CSS —
 * производный артефакт. Двойного источника правды не существует.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { schemeTokens, textStyles, tokens } from '../src/design/tokens/index.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(HERE, '..', 'src', 'styles', 'tokens.css');
const OUT_CLASS_NAMES = join(HERE, '..', 'src', 'design', 'tokens', 'class-names.generated.ts');
const BANNER = '/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand. */';

type Flat = Array<[string, string]>;

function kebab(key: string): string {
  return key
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase();
}

/** `{ a: { b: 1 } }` -> `[['a-b', '1']]` с kebab-case ключами. */
function flatten(prefix: string, value: unknown, out: Flat = []): Flat {
  if (value === null || typeof value !== 'object') {
    out.push([prefix, String(value)]);
    return out;
  }
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    flatten(prefix ? `${prefix}-${kebab(key)}` : kebab(key), child, out);
  }
  return out;
}

function block(selector: string, entries: Flat, indent = '  '): string {
  const body = entries.map(([name, value]) => `${indent}--${name}: ${value};`).join('\n');
  return `${selector} {\n${body}\n}`;
}

function buildScaleBlock(): string {
  const entries: Flat = [];
  flatten('font-family', tokens.fontFamily, entries);
  flatten('font-weight', tokens.fontWeight, entries);
  flatten('text', tokens.fontSize, entries);
  flatten('leading', tokens.lineHeight, entries);
  flatten('tracking', tokens.letterSpacing, entries);
  flatten('space', tokens.space, entries);
  flatten('layout', tokens.layout, entries);
  flatten('radius', tokens.radius, entries);
  flatten('border-width', tokens.borderWidth, entries);
  flatten('ease', tokens.easing, entries);
  flatten('duration', tokens.duration, entries);
  flatten('z', tokens.zIndex, entries);
  flatten('aspect', tokens.aspectRatio, entries);
  flatten('opacity', tokens.opacity, entries);
  flatten('scrim', tokens.scrim, entries);
  return block(':root', entries);
}

/**
 * Breakpoints регистрируются через `@theme` литеральными значениями:
 * media query не может содержать `var()`, поэтому здесь `inline`-ссылка
 * на переменную невозможна в принципе.
 */
function buildBreakpointTheme(): string {
  const entries: Flat = Object.entries(tokens.breakpoint).map(
    ([name, px]) => [`breakpoint-${name}`, `${px}px`] as [string, string],
  );
  return block('@theme', entries);
}

function buildSchemeBlocks(): string {
  return Object.entries(schemeTokens)
    .map(([scheme, { colors, shadows }]) => {
      const entries: Flat = [
        ...Object.entries(colors),
        ...Object.entries(shadows),
        ['color-scheme-name', scheme],
      ];
      const selector =
        scheme === 'light'
          ? ':root,\n[data-theme="light"]'
          : `[data-theme="${scheme}"]`;
      const extra = scheme === 'light' ? '  color-scheme: light;' : '  color-scheme: dark;';
      const body = entries.map(([n, v]) => `  --${n}: ${v};`).join('\n');
      return `${selector} {\n${extra}\n${body}\n}`;
    })
    .join('\n\n');
}

function buildTextStyleUtilities(): string {
  return Object.entries(textStyles)
    .map(([name, s]) => {
      return [
        `[data-text="${name}"], .text-${name} {`,
        `  font-family: var(--font-family-${s.family});`,
        `  font-size: var(--text-${s.size});`,
        `  font-weight: var(--font-weight-${s.weight});`,
        `  line-height: var(--leading-${s.lineHeight});`,
        `  letter-spacing: var(--tracking-${s.tracking});`,
        `}`,
      ].join('\n');
    })
    .join('\n\n');
}

/** Имена классов длительностей и слоёв: `duration-slow`, `z-header`. */
const durationClassNames = Object.keys(tokens.duration).map((name) => `duration-${kebab(name)}`);
const zIndexClassNames = Object.keys(tokens.zIndex).map((name) => `z-${kebab(name)}`);
const textStyleClassNames = Object.keys(textStyles).map((name) => `text-${name}`);

/**
 * Утилиты для шкал, у которых в Tailwind v4 НЕТ theme-namespace.
 *
 * `--ease-*` и `--color-*` Tailwind понимает сам, поэтому `ease-brand` работает.
 * А `duration-*` и `z-*` принимают только числа (`duration-300`, `z-50`) либо
 * явную переменную — поэтому `duration-slow`, написанное по аналогии, не
 * генерировало НИКАКОГО CSS: класс в разметке был, свойства не было.
 *
 * Объявляем их утилитами явно и из тех же токенов, чтобы разметка читалась
 * именами шкалы, а не числами, и чтобы CSS не мог разойтись с TypeScript.
 */
function buildScaleUtilities(): string {
  const utility = (className: string, property: string, variable: string) =>
    `@utility ${className} {\n  ${property}: var(${variable});\n}`;

  return [
    ...durationClassNames.map((className) =>
      utility(className, 'transition-duration', `--${className}`),
    ),
    ...zIndexClassNames.map((className) => utility(className, 'z-index', `--${className}`)),
  ].join('\n\n');
}

/**
 * Модуль с именами этих классов для `cn()`.
 *
 * tailwind-merge не знает наших классов и раскладывает их по группам по форме
 * имени: `text-label` попадает в группу цвета текста и МОЛЧА выбрасывается,
 * если рядом стоит `text-content-primary`. Список имён нужен, чтобы объяснить
 * ему группы; генерируется здесь, потому что источник имён — те же токены.
 *
 * Отдельный файл, а не импорт `tokens` в `cn()`: `cn` вызывается в каждом
 * компоненте, и тянуть в клиентский бандл карты цветов ради списка строк
 * незачем.
 */
function renderClassNames(): string {
  const list = (name: string, values: readonly string[]) =>
    `export const ${name} = [\n${values.map((v) => `  '${v}',`).join('\n')}\n] as const;`;

  return [
    BANNER,
    '',
    '/** Семантические стили типографики: конфликтуют друг с другом, но не с цветом. */',
    list('textStyleClassNames', textStyleClassNames),
    '',
    '/** Длительности переходов из шкалы движения. */',
    list('durationClassNames', durationClassNames),
    '',
    '/** Слои из карты z-index. */',
    list('zIndexClassNames', zIndexClassNames),
    '',
  ].join('\n');
}

function render(): string {
  return [
    BANNER,
    '',
    buildBreakpointTheme(),
    '',
    buildScaleBlock(),
    '',
    buildSchemeBlocks(),
    '',
    '/* Semantic text styles — используйте data-text="heading-2" или класс .text-heading-2 */',
    buildTextStyleUtilities(),
    '',
    '/* Шкалы без theme-namespace в Tailwind v4 — объявлены утилитами явно. */',
    buildScaleUtilities(),
    '',
  ].join('\n');
}

/** Все производные артефакты: пишутся и проверяются одним проходом. */
const artifacts: ReadonlyArray<{ file: string; content: string }> = [
  { file: OUT_FILE, content: render() },
  { file: OUT_CLASS_NAMES, content: renderClassNames() },
];

const isCheck = process.argv.includes('--check');

if (isCheck) {
  for (const { file, content } of artifacts) {
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      console.error(`tokens:check — ${file} отсутствует. Запустите: npm run tokens:build`);
      process.exit(1);
    }
    if (current.replace(/\r\n/g, '\n') !== content) {
      console.error(`tokens:check — ${file} устарел. Запустите: npm run tokens:build`);
      process.exit(1);
    }
  }
  console.log(`tokens:check — OK (${artifacts.length} артефакта)`);
} else {
  for (const { file, content } of artifacts) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content, 'utf8');
    console.log(`tokens:build — записано ${file}`);
  }
}
