/**
 * Генератор `src/styles/tokens.css` из TypeScript-токенов.
 *
 *   npm run tokens:build   — перегенерировать файл
 *   npm run tokens:check   — упасть, если файл разошёлся с TS (запускается в CI)
 *
 * Смысл: значения живут в TS (типизированы, доступны рантайму), а CSS —
 * производный артефакт. Двойного источника правды не существует.
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { schemeTokens, textStyles, tokens } from '../src/design/tokens/index.ts';
import { motion } from '../src/design/motion.ts';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_FILE = join(HERE, '..', 'src', 'styles', 'tokens.css');
const OUT_CLASS_NAMES = join(HERE, '..', 'src', 'design', 'tokens', 'class-names.generated.ts');
const BANNER = '/* AUTO-GENERATED by scripts/build-tokens.ts — do not edit by hand. */';

type Flat = Array<[string, string]>;

/**
 * `sectionYWide` -> `section-y-wide`.
 *
 * Два правила, а не одно: первое разделяет «строчная→заглавная» (`navHeight`),
 * второе — цепочку заглавных перед строчной (`sectionYWide`). Без второго
 * получалось `section-ywide`, и обращение к `--layout-section-y-wide` из кода
 * молча указывало на несуществующую переменную: у секции просто не было
 * отступов, а ошибки не было нигде.
 */
function kebab(key: string): string {
  return key
    .replace(/([A-Z]+)([A-Z][a-z])/g, '$1-$2')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .replace(/_/g, '-')
    .toLowerCase();
}

/** `{ a: { b: 1 } }` -> `[['a-b', '1']]` с kebab-case ключами. */
function flatten(prefix: string, value: unknown, out: Flat = []): Flat {
  if (value === null || typeof value !== 'object') {
    out.push([prefix, String(value)]);
    return out;
  }
  for (const [key, child] of Object.entries(value as Record<string, unknown>)) {
    flatten(prefix ? `${prefix}-${kebab(key)}` : kebab(key), child, out);
  }
  return out;
}

function block(selector: string, entries: Flat, indent = '  '): string {
  const body = entries.map(([name, value]) => `${indent}--${name}: ${value};`).join('\n');
  return `${selector} {\n${body}\n}`;
}

function buildScaleBlock(): string {
  const entries: Flat = [];
  flatten('font-family', tokens.fontFamily, entries);
  flatten('font-weight', tokens.fontWeight, entries);
  flatten('text', tokens.fontSize, entries);
  flatten('leading', tokens.lineHeight, entries);
  flatten('tracking', tokens.letterSpacing, entries);
  flatten('space', tokens.space, entries);
  flatten('layout', tokens.layout, entries);
  flatten('radius', tokens.radius, entries);
  flatten('border-width', tokens.borderWidth, entries);
  flatten('ease', tokens.easing, entries);
  flatten('duration', tokens.duration, entries);
  flatten('z', tokens.zIndex, entries);
  flatten('aspect', tokens.aspectRatio, entries);
  flatten('opacity', tokens.opacity, entries);
  flatten('scrim', tokens.scrim, entries);
  flatten('mask', tokens.mask, entries);
  return block(':root', entries);
}

/**
 * Breakpoints регистрируются через `@theme` литеральными значениями:
 * media query не может содержать `var()`, поэтому здесь `inline`-ссылка
 * на переменную невозможна в принципе.
 */
function buildBreakpointTheme(): string {
  const entries: Flat = Object.entries(tokens.breakpoint).map(
    ([name, px]) => [`breakpoint-${name}`, `${px}px`] as [string, string],
  );
  return block('@theme', entries);
}

function buildSchemeBlocks(): string {
  const blocks = Object.entries(schemeTokens).map(([scheme, { colors, shadows }]) => {
    const entries: Flat = [
      ...Object.entries(colors),
      ...Object.entries(shadows),
      ['color-scheme-name', scheme],
    ];
    const selector =
      scheme === 'light' ? ':root,\n[data-theme="light"]' : `[data-theme="${scheme}"]`;
    const extra = scheme === 'light' ? '  color-scheme: light;' : '  color-scheme: dark;';
    const body = entries.map(([n, v]) => `  --${n}: ${v};`).join('\n');
    return `${selector} {\n${extra}\n${body}\n}`;
  });

  return [...blocks, buildSystemDarkBlock()].join('\n\n');
}

/**
 * Тёмная тема по системной настройке — для тех, кто ещё не выбирал вручную.
 *
 * Селектор `:root:not([data-theme])` важен: как только пользователь сделал выбор,
 * атрибут появляется, и системная настройка больше не перебивает его решение.
 *
 * Зачем это нужно, если выбор темы всё равно делает скрипт: без такого блока
 * страница с выключенным JavaScript всегда светлая, даже у пользователя с тёмной
 * системой. И это же правило убирает мигание в тот единственный кадр, когда
 * разметка уже отрисована, а скрипт ещё не выставил атрибут.
 */
function buildSystemDarkBlock(): string {
  const { colors, shadows } = schemeTokens.dark;
  const entries: Flat = [
    ...Object.entries(colors),
    ...Object.entries(shadows),
    ['color-scheme-name', 'dark'],
  ];
  const body = entries.map(([n, v]) => `    --${n}: ${v};`).join('\n');
  return [
    '@media (prefers-color-scheme: dark) {',
    '  :root:not([data-theme]) {',
    '    color-scheme: dark;',
    body,
    '  }',
    '}',
  ].join('\n');
}

function buildTextStyleUtilities(): string {
  return Object.entries(textStyles)
    .map(([name, s]) => {
      const style = s as {
        family: string;
        size: string;
        weight: string;
        lineHeight: string;
        tracking: string;
        wrap?: string;
        numeric?: string;
      };
      const lines = [
        `[data-text="${name}"], .text-${name} {`,
        `  font-family: var(--font-family-${style.family});`,
        `  font-size: var(--text-${style.size});`,
        `  font-weight: var(--font-weight-${style.weight});`,
        `  line-height: var(--leading-${style.lineHeight});`,
        `  letter-spacing: var(--tracking-${style.tracking});`,
      ];

      /*
       * Перенос строк — часть стиля, а не украшение у места вызова.
       *
       * `balance` для заголовков: без него в display-кегле последняя строка
       * регулярно остаётся одним словом, и это видно в макете. `pretty` для
       * основного текста: та же задача, но дешевле — `balance` на длинном
       * абзаце заставляет браузер перебирать варианты и стоит кадров.
       */
      if (style.wrap) lines.push(`  text-wrap: ${style.wrap};`);

      /*
       * Табличные цифры там, где числа сравнивают или где они меняются на
       * месте. Без них счётчик показателей дёргает раскладку на каждом кадре
       * (у пропорциональной «1» ширина меньше, чем у «8»), а колонка цен не
       * выравнивается по разрядам.
       */
      if (style.numeric) lines.push(`  font-variant-numeric: ${style.numeric};`);

      lines.push('}');
      return lines.join('\n');
    })
    .join('\n\n');
}

/** Имена классов длительностей и слоёв: `duration-slow`, `z-header`. */
const durationClassNames = Object.keys(tokens.duration).map((name) => `duration-${kebab(name)}`);
const zIndexClassNames = Object.keys(tokens.zIndex).map((name) => `z-${kebab(name)}`);
const textStyleClassNames = Object.keys(textStyles).map((name) => `text-${name}`);

/**
 * Утилиты для шкал, у которых в Tailwind v4 НЕТ theme-namespace.
 *
 * `--ease-*` и `--color-*` Tailwind понимает сам, поэтому `ease-brand` работает.
 * А `duration-*` и `z-*` принимают только числа (`duration-300`, `z-50`) либо
 * явную переменную — поэтому `duration-slow`, написанное по аналогии, не
 * генерировало НИКАКОГО CSS: класс в разметке был, свойства не было.
 *
 * Длительность обязана писать И `--tw-duration`, И `transition-duration`.
 * Причина в устройстве самих утилит Tailwind: `transition`, `transition-colors`
 * и `transition-[…]` объявляют
 * `transition-duration: var(--tw-duration, var(--default-transition-duration))`,
 * то есть перебивают прямое значение обратно на 150ms по умолчанию. Именно из-за
 * этого переходы на карточках выглядели резкими: класс `duration-slow` стоял,
 * а работали дефолтные 150ms.
 */
function buildScaleUtilities(): string {
  const durationUtility = (className: string) =>
    [
      `@utility ${className} {`,
      `  --tw-duration: var(--${className});`,
      `  transition-duration: var(--${className});`,
      '}',
    ].join('\n');

  const layerUtility = (className: string) =>
    `@utility ${className} {\n  z-index: var(--${className});\n}`;

  return [
    ...durationClassNames.map(durationUtility),
    ...zIndexClassNames.map(layerUtility),
  ].join('\n\n');
}

/**
 * Модуль с именами этих классов для `cn()`.
 *
 * tailwind-merge не знает наших классов и раскладывает их по группам по форме
 * имени: `text-label` попадает в группу цвета текста и МОЛЧА выбрасывается,
 * если рядом стоит `text-content-primary`. Список имён нужен, чтобы объяснить
 * ему группы; генерируется здесь, потому что источник имён — те же токены.
 *
 * Отдельный файл, а не импорт `tokens` в `cn()`: `cn` вызывается в каждом
 * компоненте, и тянуть в клиентский бандл карты цветов ради списка строк
 * незачем.
 */
function renderClassNames(): string {
  const list = (name: string, values: readonly string[]) =>
    `export const ${name} = [\n${values.map((v) => `  '${v}',`).join('\n')}\n] as const;`;

  return [
    BANNER,
    '',
    '/** Семантические стили типографики: конфликтуют друг с другом, но не с цветом. */',
    list('textStyleClassNames', textStyleClassNames),
    '',
    '/** Длительности переходов из шкалы движения. */',
    list('durationClassNames', durationClassNames),
    '',
    '/** Слои из карты z-index. */',
    list('zIndexClassNames', zIndexClassNames),
    '',
  ].join('\n');
}

/**
 * Параметры сценариев движения, которые нужны и CSS, и JavaScript.
 *
 * Появление секций описано в CSS (переход и конечное состояние), а запускается
 * из JS (IntersectionObserver с порогом и rootMargin). Смещение «60px» знают оба
 * — значит, оно обязано существовать в одном месте. Источник — `motion.ts`,
 * здесь только перенос с добавлением единиц.
 *
 * Соответствие вручную, а не автоматическим обходом объекта: в TS значения
 * лежат числами (`durationMs: 900`), а CSS нужны единицы, и `--…-ms: 900`
 * было бы непригодно для `transition`.
 */
function buildMotionBlock(): string {
  const entries: Flat = [
    ['reveal-duration', `${motion.reveal.durationMs}ms`],
    ['reveal-easing', motion.reveal.easing],
    ['reveal-offset-up', motion.reveal.offset.up],
    ['reveal-offset-side', motion.reveal.offset.side],
    ['reveal-scale-from', String(motion.reveal.offset.scale)],
    ['stagger-duration', `${motion.stagger.durationMs}ms`],
    ['stagger-base-delay', `${motion.stagger.baseDelayMs}ms`],
    ['stagger-step', `${motion.stagger.stepMs}ms`],
    ['stagger-offset', `${motion.stagger.offsetPx}px`],
    ['scroll-progress-height', `${motion.scrollProgress.heightPx}px`],
    ['scroll-progress-transition', `${motion.scrollProgress.transitionMs}ms`],
    ['pointer-glow-size', `${motion.pointerGlow.sizePx}px`],
    ['pointer-glow-fade', `${motion.pointerGlow.fadeMs}ms`],
    ['card-tilt-perspective', `${motion.cardTilt.perspectivePx}px`],
    ['card-tilt-rotate', `${motion.cardTilt.maxRotateDeg}deg`],
    ['card-tilt-lift', `${motion.cardTilt.liftPx}px`],
    ['card-tilt-scale', String(motion.cardTilt.scale)],
    /** Геометрия и вид шлейфа фоновой петли — числа из прототипа. */
    ['hero-wrap-width', `${motion.heroGhostTrail.wrapWidthPercent}%`],
    ['hero-ghost-opacity', String(motion.heroGhostTrail.opacity)],
    ['hero-ghost-filter', motion.heroGhostTrail.filter],
  ];
  return block(':root', entries);
}

/** Задержки stagger: по одному правилу на позицию ребёнка, до `maxChildren`. */
function buildStaggerDelays(): string {
  const rules: string[] = [];
  for (let index = 1; index <= motion.stagger.maxChildren; index += 1) {
    rules.push(
      `  [data-stagger][data-revealed] > *:nth-child(${index}) {\n` +
        `    transition-delay: calc(var(--stagger-base-delay) + var(--stagger-step) * ${index - 1});\n` +
        `  }`,
    );
  }
  return rules.join('\n');
}

/** Правила появления: скрытое состояние, конечное состояние и задержки stagger. */
function buildRevealRules(): string {
  return [
    '@media (scripting: enabled) and (prefers-reduced-motion: no-preference) {',
    '  [data-reveal] {',
    '    opacity: 0;',
    '    transition:',
    '      opacity var(--reveal-duration) var(--reveal-easing),',
    '      transform var(--reveal-duration) var(--reveal-easing);',
    '  }',
    '',
    '  [data-reveal="up"] {',
    '    transform: translateY(var(--reveal-offset-up));',
    '  }',
    '',
    '  [data-reveal="left"] {',
    '    transform: translateX(calc(var(--reveal-offset-side) * -1));',
    '  }',
    '',
    '  [data-reveal="right"] {',
    '    transform: translateX(var(--reveal-offset-side));',
    '  }',
    '',
    '  [data-reveal="scale"] {',
    '    transform: scale(var(--reveal-scale-from));',
    '  }',
    '',
    '  [data-reveal][data-revealed] {',
    '    opacity: 1;',
    '    transform: none;',
    '  }',
    '',
    '  /* Контейнер stagger сам не двигается — двигаются его дети. */',
    '  [data-stagger] > * {',
    '    opacity: 0;',
    '    transform: translateY(var(--stagger-offset));',
    '    transition:',
    '      opacity var(--stagger-duration) var(--reveal-easing),',
    '      transform var(--stagger-duration) var(--reveal-easing);',
    '  }',
    '',
    '  [data-stagger][data-revealed] > * {',
    '    opacity: 1;',
    '    transform: none;',
    '  }',
    '',
    buildStaggerDelays(),
    '}',
  ].join('\n');
}

function render(): string {
  return [
    BANNER,
    '',
    buildBreakpointTheme(),
    '',
    buildScaleBlock(),
    '',
    buildMotionBlock(),
    '',
    buildSchemeBlocks(),
    '',
    '/* Semantic text styles — используйте data-text="heading-2" или класс .text-heading-2 */',
    buildTextStyleUtilities(),
    '',
    '/* Шкалы без theme-namespace в Tailwind v4 — объявлены утилитами явно. */',
    buildScaleUtilities(),
    '',
    '/*',
    ' * Появление блоков при прокрутке.',
    ' *',
    ' * Скрытое состояние объявлено ТОЛЬКО внутри двух условий:',
    ' *   • `scripting: enabled` — без JavaScript наблюдатель не запустится и',
    ' *     контент остался бы навсегда прозрачным. В прототипе именно так:',
    ' *     `.reveal { opacity: 0 }` в статическом CSS. Это не украшение, это',
    ' *     потеря контента, поэтому условие обязательно;',
    ' *   • `prefers-reduced-motion: no-preference` — при просьбе убрать движение',
    ' *     блок обязан сразу быть в конечном состоянии, а не появляться мгновенно.',
    ' *',
    ' * Значения смещений и длительностей — из `src/design/motion.ts`.',
    ' */',
    buildRevealRules(),
    '',
  ].join('\n');
}

/** Все производные артефакты: пишутся и проверяются одним проходом. */
const artifacts: ReadonlyArray<{ file: string; content: string }> = [
  { file: OUT_FILE, content: render() },
  { file: OUT_CLASS_NAMES, content: renderClassNames() },
];

const isCheck = process.argv.includes('--check');

if (isCheck) {
  for (const { file, content } of artifacts) {
    let current = '';
    try {
      current = readFileSync(file, 'utf8');
    } catch {
      console.error(`tokens:check — ${file} отсутствует. Запустите: npm run tokens:build`);
      process.exit(1);
    }
    if (current.replace(/\r\n/g, '\n') !== content) {
      console.error(`tokens:check — ${file} устарел. Запустите: npm run tokens:build`);
      process.exit(1);
    }
  }
  console.log(`tokens:check — OK (${artifacts.length} артефакта)`);
} else {
  for (const { file, content } of artifacts) {
    mkdirSync(dirname(file), { recursive: true });
    writeFileSync(file, content, 'utf8');
    console.log(`tokens:build — записано ${file}`);
  }
}
