/* AUTO-GENERATED by scripts/encode-hero-video.ts — do not edit by hand. */

/**
 * Фоновая петля первого экрана: реальные файлы и их вес.
 *
 * Вес хранится здесь, а не считается в рантайме: он нужен отчётам о бюджете и
 * админке до того, как браузер что-то скачает.
 */
export interface HeroVideoSourceFile {
  format: 'av1' | 'vp9' | 'h264';
  /** Имя файла в `public/media/video`. */
  file: string;
  bytes: number;
}

export const heroVideoSources: readonly HeroVideoSourceFile[] = [
  { format: 'av1', file: 'hero-loop.av1.mp4', bytes: 604705 },
  { format: 'vp9', file: 'hero-loop.webm', bytes: 680397 },
  { format: 'h264', file: 'hero-loop.mp4', bytes: 1100915 },
];

/** Длительность петли, секунды. */
export const heroVideoDurationSeconds = 8;
