/* AUTO-GENERATED by scripts/encode-video-loops.ts — do not edit by hand. */

/**
 * Фоновые петли: реальные файлы, их ширина и вес.
 *
 * Вес хранится здесь, а не считается в рантайме: он нужен отчётам о бюджете и
 * админке до того, как браузер что-то скачает. Ширина нужна выбору источника:
 * узкому экрану незачем качать кадр вчетверо шире, чем он его показывает.
 */
import type { VideoLoopKey } from '@/config/media-processing';

export interface VideoLoopSourceFile {
  format: 'av1' | 'vp9' | 'h264';
  /** Ширина кадра в пикселях. */
  width: number;
  /** Имя файла в `public/media/video`. */
  file: string;
  bytes: number;
}

export interface VideoLoopManifest {
  sources: readonly VideoLoopSourceFile[];
  /** Длительность петли, секунды. После склейки шва короче исходника. */
  durationSeconds: number;
}

export const videoLoops: Record<VideoLoopKey, VideoLoopManifest> = {
  hero: {
    sources: [
      { format: 'av1', width: 1280, file: 'hero-loop-1280-282e6703.av1.mp4', bytes: 772629 },
      { format: 'vp9', width: 1280, file: 'hero-loop-1280-c477b11e.webm', bytes: 867473 },
      { format: 'h264', width: 1280, file: 'hero-loop-1280-4847989e.mp4', bytes: 1339472 },
      { format: 'av1', width: 1920, file: 'hero-loop-1920-e8edfb52.av1.mp4', bytes: 1233120 },
      { format: 'vp9', width: 1920, file: 'hero-loop-1920-cbc52919.webm', bytes: 1504106 },
      { format: 'h264', width: 1920, file: 'hero-loop-1920-500f7022.mp4', bytes: 2286726 },
    ],
    durationSeconds: 8,
  },
  editorial: {
    sources: [
      { format: 'av1', width: 720, file: 'editorial-loop-720-a5f2bf8b.av1.mp4', bytes: 521731 },
      { format: 'vp9', width: 720, file: 'editorial-loop-720-f420610c.webm', bytes: 613071 },
      { format: 'h264', width: 720, file: 'editorial-loop-720-861269ae.mp4', bytes: 1079669 },
      { format: 'av1', width: 1280, file: 'editorial-loop-1280-c33a659c.av1.mp4', bytes: 1000968 },
      { format: 'vp9', width: 1280, file: 'editorial-loop-1280-7d2bb97f.webm', bytes: 1249756 },
      { format: 'h264', width: 1280, file: 'editorial-loop-1280-a0a10445.mp4', bytes: 2172837 },
    ],
    durationSeconds: 8.5,
  },
};
