/* AUTO-GENERATED by scripts/encode-video-loops.ts — do not edit by hand. */

/**
 * Фоновые петли: реальные файлы, их ширина и вес.
 *
 * Вес хранится здесь, а не считается в рантайме: он нужен отчётам о бюджете и
 * админке до того, как браузер что-то скачает. Ширина нужна выбору источника:
 * узкому экрану незачем качать кадр вчетверо шире, чем он его показывает.
 */
import type { VideoLoopKey } from '@/config/media-processing';

export interface VideoLoopSourceFile {
  format: 'av1' | 'vp9' | 'h264';
  /** Ширина кадра в пикселях. */
  width: number;
  /** Имя файла в `public/media/video`. */
  file: string;
  bytes: number;
}

export interface VideoLoopManifest {
  sources: readonly VideoLoopSourceFile[];
  /** Длительность петли, секунды. После склейки шва короче исходника. */
  durationSeconds: number;
}

export const videoLoops: Record<VideoLoopKey, VideoLoopManifest> = {
  hero: {
    sources: [
      { format: 'av1', width: 1280, file: 'hero-loop-1280-a44a1835.av1.mp4', bytes: 653691 },
      { format: 'vp9', width: 1280, file: 'hero-loop-1280-5d9a435e.webm', bytes: 1347706 },
      { format: 'h264', width: 1280, file: 'hero-loop-1280-bbd88caf.mp4', bytes: 1520346 },
      { format: 'av1', width: 1920, file: 'hero-loop-1920-d8d237b3.av1.mp4', bytes: 803748 },
      { format: 'vp9', width: 1920, file: 'hero-loop-1920-ef40dbe8.webm', bytes: 2002938 },
      { format: 'h264', width: 1920, file: 'hero-loop-1920-2f45ca55.mp4', bytes: 2322420 },
    ],
    durationSeconds: 10,
  },
  heroReverse: {
    sources: [
      { format: 'av1', width: 1280, file: 'hero-loop-reverse-1280-2181cb93.av1.mp4', bytes: 823010 },
      { format: 'vp9', width: 1280, file: 'hero-loop-reverse-1280-0756c841.webm', bytes: 1184117 },
      { format: 'h264', width: 1280, file: 'hero-loop-reverse-1280-1f043d80.mp4', bytes: 1329887 },
      { format: 'av1', width: 1920, file: 'hero-loop-reverse-1920-a162b20f.av1.mp4', bytes: 1356149 },
      { format: 'vp9', width: 1920, file: 'hero-loop-reverse-1920-4a2b41e0.webm', bytes: 1858355 },
      { format: 'h264', width: 1920, file: 'hero-loop-reverse-1920-98043d40.mp4', bytes: 2057397 },
    ],
    durationSeconds: 10,
  },
  editorial: {
    sources: [
      { format: 'av1', width: 720, file: 'editorial-loop-720-a5f2bf8b.av1.mp4', bytes: 521731 },
      { format: 'vp9', width: 720, file: 'editorial-loop-720-f420610c.webm', bytes: 613071 },
      { format: 'h264', width: 720, file: 'editorial-loop-720-861269ae.mp4', bytes: 1079669 },
      { format: 'av1', width: 1280, file: 'editorial-loop-1280-c33a659c.av1.mp4', bytes: 1000968 },
      { format: 'vp9', width: 1280, file: 'editorial-loop-1280-7d2bb97f.webm', bytes: 1249756 },
      { format: 'h264', width: 1280, file: 'editorial-loop-1280-a0a10445.mp4', bytes: 2172837 },
    ],
    durationSeconds: 8.5,
  },
};
